### PR TITLE
Update test-wasms to use release sdk/env and add contract that can transfer using the SAC

### PR DESCRIPTION
**Pull request by sisuresh**
Required for https://github.com/stellar/rs-soroban-env/issues/912.

I'm surprised that the test wasms were still being built with rc2 and that we didn't have any issues... (EDIT: nvm we use a local patch for env and sdk when building test wasms)

### CODE REVIEW

**Comment by sisuresh** [comment]
@jayz22 I think the the observation updates in this PR are due to the cost model updates. Is this expected?

**Comment by dmkozh** [comment]
Do we really need to update all the Wasms? Why not just add the new one?

**Comment by sisuresh** [comment]
> Do we really need to update all the Wasms? Why not just add the new one?

Good point. I thought I had to make an update because rc2 was specified in the TOML file, but that was wrong. Updated.

**Comment by dmkozh** [comment]
> I thought I had to make an update because rc2 was specified in the TOML file, but that was wrong

FWIW now that the protocol is frozen, these Wasms can be considered frozen as well, at least in terms of the SDK/env versions (we should be able to run them in every future versions).

**Review by dmkozh — APPROVED** [review]

**Comment by sisuresh** [comment]
> > I thought I had to make an update because rc2 was specified in the TOML file, but that was wrong
> 
> FWIW now that the protocol is frozen, these Wasms can be considered frozen as well, at least in terms of the SDK/env versions (we should be able to run them in every future versions).

Is this true? We can technically update the sdk version and still rebuild a v20 compatible contract right?

**Comment by dmkozh** [comment]
> Is this true? We can technically update the sdk version and still rebuild a v20 compatible contract right?

Sure, I mean that the old contracts have to remain compatible. Newer contracts should of course be compatible as well. Just saying that it's valuable to keep the older contracts around as a simple sanity check.

**Pull request merged**
