### PR TITLE
Forbid contract reentry

### PR DESCRIPTION
**Pull request by jayz22**
### What

Partially resolves https://github.com/stellar/rs-soroban-env/issues/336. 

~Add a `reentry: RawVal` argument to the `try_call` function. If set, it checks the host context for frames with the same contract id.~
Disallow contract reentry by checking the host context for frames with the same contract id. 
In a later follow up, we will add a `reentry: RawVal` flag to the `try_call` function and use that. 

### Why

- Why there is no checking function name? We assume if reentry is disabled, the same contract cannot be entered at all, even if the entry point is a different function than what had been called. 
- (In the future) Why only add it in `try_call`?  The `call` host function is the recommended (safe) path of invocation, where any failure will results in an host error.  The `try_call` is the more loose version that allows failure to be returned as a status. It makes sense to only enable re-entry in the `try_call` invocation path since that is a further loosening feature (@graydon has suggested it). 

### Known limitations

[TODO or N/A]

### CODE REVIEW

**Comment by jayz22** [comment]
I haven't bumped the env version because I haven't figured out how to make the sdk changes (proc-macro) in order to regen the wasm tests.

**Review by leighmcculloch — APPROVED** [review]
This looks good to me, but I'm a little confused by the comment that has been added, since it is incorrect in the context of testing.

**Comment by leighmcculloch** [comment]
> It makes sense to only enable re-entry in the try_call invocation path since that is a further loosening feature (@graydon has suggested it).

I don't think it makes sense to couple reentry as a capability with error handling, as there are disconnected reasons to choose one and the other.

In the SDK I hope to add support for "invocation options" on functions that call both call and try_call, and it will muddy the SDK API if these options are inconsistent between the two functions.

At the moment these options will only include the reentry flag, but I imagine them including other options in the future.

cc @graydon

**Review by graydon — APPROVED** [review]
LGTM! Thanks!

**Comment by leighmcculloch** [comment]
@jayz22 I think we should add new call and try_call functions that take the additional option. I think we can simply call them `call_2` and `try_call_2`, and each time we add a new option we can add a new host function.

**Pull request merged**
