### PR TITLE
Native token contract wrapper interface

### LINKED ISSUE #316: Add host functions to support token wrapper interface
Related to https://github.com/stellar/soroban-token-contract/issues/5 and #175

### PR DESCRIPTION
**Pull request by jonjove**
### What

Resolves #316, https://github.com/stellar/soroban-token-contract/issues/5, and https://github.com/stellar/soroban-token-contract/issues/80

### Why

Interoperability with classic.

### Known limitations

No tests yet so it might not actually work

### CODE REVIEW

**Comment by jonjove** [comment]
I'm going to resolve conflicts and merge this. We can figure out how to test it after.

**Comment by leighmcculloch** [comment]
> No tests yet so it might not actually work

> We can figure out how to test it after.

More recently we've started to chew time on things that weren't tested in the host. I think there would be some value in verifying this works with some basic tests, especially if we are suspicious it doesn't work.

**Comment by jonjove** [comment]
I'm not saying we shouldn't test it. I'm saying I want to merge this so it doesn't get stale again.

**Comment by leighmcculloch** [comment]
cc @sisuresh @dmkozh since I think you'll possibly be picking this and #428 up.

**Pull request merged**
