### PR TITLE
Include token name in all token events

### PR DESCRIPTION
**Pull request by tamirms**
### What

Include the token name in the data scval for all events emitted by the native asset contract

### Why

In https://github.com/stellar/go/issues/4722#issuecomment-1363317232 I had a discussion with @sisuresh about how it would be useful for horizon ingestion to be able to identify if a contract id corresponds the stellar asset contract. We need this information so that we can identify transfers of Stellar assets that were initiated via a smart contract invocation as opposed to a stellar classic payment operation.

@sisuresh was understandably reluctant to add an extra flag in the xdr definitions so that we could identify that a contract id corresponds to a stellar asset. So after some brainstorming we determined that if the events emitted by a stellar asset contract included the asset issuer and symbol we would be able to determine whether the event originated from a stellar asset contract because we can hash the asset symbol and issuer from the contract event and check that the hash matches the contract's id.  

### Known limitations

[N/A]

### CODE REVIEW

**Review by sisuresh — COMMENTED** [review]
This adds data to the events that will not be used by most consumers. These events are also standard, so other WASM token implementations would either follow this, or leave it out, resulting in special handling for SAC events.

I'd like to discuss possible solutions before committing to an idea like this.

**Comment by tsachiherman** [comment]
> This adds data to the events that will not be used by most consumers. These events are also standard, so other WASM token implementations would either follow this, or leave it out, resulting in special handling for SAC events.
> 
> I'd like to discuss possible solutions before committing to an idea like this.

maybe I'm missing something, but my understanding is that at this point in time **the only consumer** for that data is the platform team. I understand that other WASM token implementation might not have these features - and that's perfectly fine. The reason this is needed is to provide a proper "bridging" between the existing classic asset and token assets.

This is not materially any different then the special handling we're currently providing in core for manipulating token assets.

I'd be happy do sync up with you additional solutions we've explored.

**Comment by leighmcculloch** [comment]
I think it's okay if the stellar asset contract extends the events of the token interface. The token interface needs to be extendable I think. 

But even if the data existed in the events, how would Horizon distinguish between events from a stellar asset contract linked to a Stellar asset and another contract masquerading as a Stellar asset contract?

Given there's incentives for contracts to masquerade as a Stellar asset, the identification of which asset it is should probably be authenticated in some way. We could achieve this by putting the information in the meta.

**Comment by tsachiherman** [comment]
> I think it's okay if the stellar asset contract extends the events of the token interface. The token interface needs to be extendable I think.
> 
> But even if the data existed in the events, how would Horizon distinguish between events from a stellar asset contract linked to a Stellar asset and another contract masquerading as a Stellar asset contract?
> 
> Given there's incentives for contracts to masquerade as a Stellar asset, the identification of which asset it is should probably be authenticated in some way. We could achieve this by putting the information in the meta instead of in the event.

I believe that @tamirms cover the validation method above; it involves calculating the hash of and comparing it to the contract id, which guarantee that's legit. Yes, we could definitely place that information in the metadata, but it might seems that we're making a "special case" for that contract instead of just extending this contract. i.e. at the end of the day, we'd like to have the info in the ledgerclosemeta.

**Comment by sisuresh** [comment]
> maybe I'm missing something, but my understanding is that at this point in time the only consumer for that data is the platform team.

We still expect other systems to be created that will consume events right? Extending the events in this contract is fine, but because Horizon will be the only consumer of the additional information, I'm thinking it would be ideal if this information could be conveyed in a different way. If not, then the change in this PR is probably fine.

Another option that might be cleaner is adding another `ContractEventType` [here](https://github.com/stellar/stellar-xdr/blob/df18148747e807618acf4639db41c4fd6f0be9fc/Stellar-ledger.x#L391) that will only be used by the Stellar Asset Contract (something like `BUILT_IN_TOKEN`). @tamirms would that work for your use case?

**Comment by sisuresh** [comment]
I spoke to Tamir and opened an issue related to this - https://github.com/stellar/rs-soroban-env/issues/691.

**Comment by tomerweller** [comment]
Can we solve this on the horizon side? IIRC Horizon has an `assets` table, if we add an indexed `soroban_address` column , could we associate token events to an asset by looking up by the emitting contract address?

**Comment by tomerweller** [comment]
> the horizon assets table only includes assets which have at least one trustline

Sounds like we can solve this by introducing a SAC initialization event and having horizon create an asset row when ingesting this event

**Comment by Shaptic** [comment]
Was there follow-up on this approach?

> Sounds like we can solve this by introducing a SAC initialization event

My question is: Can this event be spoofed by non-SACs?

**Comment by sisuresh** [comment]
> My question is: Can this event be spoofed by non-SACs?

Not if the event emits the asset information required to calculate the contractID. The consumer could then verify that contractID against the contractID on the event.

**Comment by sreuland** [comment]
> > the horizon assets table only includes assets which have at least one trustline
> 
> Sounds like we can solve this by introducing a SAC initialization event and having horizon create an asset row when ingesting this event

what if an horizon instance starts ingesting forward-only after the SAC initialization event was already emitted on prior ledgers? Would it effectively miss that event, and not get asset table in correct state? seems like having an event model that includes some form of `symbol:issuer` if relevant such as SACs, may give clients(horizon being the first) ability to understand the event independent of anything else.

**Comment by Shaptic** [comment]
> Not if the event emits the asset information required to calculate the contractID. The consumer could then verify that contractID against the contractID on the event.

Ah, gotcha. So based on this:

https://github.com/stellar/rs-soroban-env/blob/fdfc5411368bc4433365b71d96de9e1e0f419f30/soroban-env-host/src/host.rs#L831-L835

you're saying the SAC initialize event would emit asset deets, then the consumer (e.g. Horizon) just does the same hash calculation to ensure it matches `event.contract_id`.

How does this work for nested contract calls? For example, can a non-SAC contract initialize a SAC? Then, wouldn't the `event.contract_id` not match?

-----------------

> what if an horizon instance starts ingesting forward-only after the SAC initialization event was already emitted on prior ledgers?

Good question @sreuland - this is pretty distinct from how asset information works today, since it's a property of current state which is always available w/o ingestion.

Spitballing ideas: Can/should we make the SAC emit its entire "current state" as an event on _any_ "write" interaction? Can/should we make Horizon _actually interact_ with the VM to get SAC state information (i.e. invoke the SAC)?

**Comment by sisuresh** [comment]
> you're saying the SAC initialize event would emit asset deets, then the consumer (e.g. Horizon) just does the same hash calculation to ensure it matches event.contract_id.

Correct, and just to be clear, this idea is what Tamir is relying on in the current PR as well.

> How does this work for nested contract calls? For example, can a non-SAC contract initialize a SAC? Then, wouldn't the event.contract_id not match?

Events from a nested contract call will contain the contractID of the nested contract. So if contract A calls `xfer` on an SAC, the `transfer` event will contain the SAC's contractID. This isn't really relevant here, but I'll mention that the SAC is automatically initialized on deployment, so no contract or user can call the initialization function on it. A contract also can't deploy the SAC at the moment.

**Comment by paulbellamy** [comment]
We should definitely emit "ContractInstalled" events for all contracts (SAC or otherwise), but one downside of relying on that for this case, is that it means that any downstream ingesters must be stateful (which complicates them). i.e. In order to make sense of a Transfer event, they must first see the SAC's ContractInstalled event, because a Transfer (or other) event by itself would be missing the asset id.

> This adds data to the events that will not be used by most consumers.

I think this data would be used by almost all consumers of these events. Being able to map an SAC event back to the affected asset seems pretty critical.

**Comment by tsachiherman** [comment]
> 

I think that this is an important observation. What can we do to validate that claim + support the end user flow ( maybe some extra functionality on the sdks ? )

**Pull request closed without merging**
